workflows:
  main-pipeline:
    name: Pipeline Principal
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Información del entorno
        script: |
          echo "🚀 INICIANDO BUILD EN CODEMAGIC"
          echo "Flutter Version: $(flutter --version | head -1)"
          echo "Dart Version: $(dart --version)"
          flutter clean
          flutter pub get
          echo "✅ Dependencias instaladas"
      
      - name: Análisis de código
        script: |
          echo "🔍 EJECUTANDO ANÁLISIS..."
          flutter analyze
          echo "✅ Análisis completado sin errores"
      
      - name: Ejecutar tests
        script: |
          echo "🧪 EJECUTANDO TESTS..."
          flutter test
          echo "✅ Todos los tests pasaron"
      
      - name: Build Android Release
        script: |
          echo "🤖 CONSTRUYENDO ANDROID RELEASE..."
          flutter build appbundle --release
          echo "✅ Android AAB generado: $(ls -la build/app/outputs/bundle/release/*.aab)"
      
      - name: Build iOS Release (sin firma)
        script: |
          echo "🍏 CONSTRUYENDO iOS RELEASE..."
          flutter build ios --release --no-codesign
          echo "✅ iOS IPA generado"
      
      - name: Verificación final
        script: |
          echo "📊 RESUMEN FINAL DEL BUILD:"
          echo "================================="
          echo "✅ Análisis de código: COMPLETADO"
          echo "✅ Tests: 6 PASARON"
          echo "✅ Android AAB: GENERADO"
          echo "✅ iOS IPA: GENERADO"
          echo "🎉 PIPELINE COMPLETADO EXITOSAMENTE"
          echo "================================="
    
    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa
      - build/app/outputs/apk/release/*.apk
    
    publishing:
      email:
        recipients:
          - miltonbass@gmail.com   
        notify:
          success: true
          failure: true
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true